# Generated by Django 4.0.5 on 2022-06-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.TextField()),
                ('provincia', models.TextField()),
                ('departamento', models.TextField()),
            ],
        ),
    ]
